# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileinfo',
            old_name='public_emial',
            new_name='public_email',
        ),
        migrations.AlterField(
            model_name='profileinfo',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
