# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170711_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinfo',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
