# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 07:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_appointments'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='color',
            field=models.CharField(default='blue', max_length=10),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='url',
            field=models.TextField(null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
