# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170720_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
