# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20170720_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
