# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 08:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20170720_0813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='url',
        ),
    ]
