# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_forum'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forum',
            name='image',
            field=models.URLField(blank=True, max_length=500, verbose_name='Image URL'),
        ),
    ]
