# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20170804_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
