# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20170806_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='question',
            field=models.CharField(max_length=500),
        ),
    ]
