# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20170806_0355'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=1000)),
                ('image', models.URLField(blank=True, max_length=500, verbose_name='Image URL')),
                ('url', models.URLField(blank=True, max_length=500, verbose_name='URL')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('answered_by', models.CharField(blank=True, max_length=50, null=True)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Forum')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
